### PR TITLE
feat: remove Delete and Archive

### PR DESCRIPTION
**Pull request by yansal**
We would like to reduce the scope of makroud so that it's easier to make
changes. Those two functions can be implemented outside of makroud.

### CODE REVIEW

**Review by novln — CHANGES_REQUESTED** [review]
As an user of a _light_ ORM, I expect to be able to delete object _(or archive)_ with it.

Without having more context about what you want to change in makroud, I'm against this removal.

**Comment by thoas** [comment]
the idea is to simplify makroud and reduce features, we don’t use these functions internally so less code to maintain. Let us know if you still use them on your side.

**Comment by novln** [comment]
I understand that you don't use these features. But like [Transaction Option](https://github.com/ulule/makroud/blob/master/transaction.go#L18), the [Select helper](https://github.com/ulule/makroud/blob/master/select.go#L18) or even the [Save helper](https://github.com/ulule/makroud/blob/master/save.go#L14), I think they are great features for someone that want a light ORM, without too much complexity.

Currently, you either have the choice to use code generation (like [Ent framework](https://github.com/facebook/ent)) or deal with the hassle that Gorm is. I think it's great that makroud is on a sweat spot so you can do complex queries directly on the driver if you're a power user, or use the helpers with models if you want something really simple and don't want to overthink it.

And in my opinion, deletion is a required feature for this toolbox. Like, if you want to create a simple CRUD API, it would be a shame that your connector doesn't support deletion, and does _"everything"_ else.

So the real question is: what is the new scope of `makroud` ? Because if it hasn't changed _(an open source alternative to Gorm)_, I don't understand this choice except to reduce the number of LOC...

Finally, I don't use makroud on my side to be honest _(but I want/plan to)_. 
Could I re-introduce this feature if this change ?

Anyway, this is my opinion on the subject. 

PS:

From what Yann said:
> We would like to reduce the scope of makroud so that **it's easier to make
changes**.

I understand that you want to do a refactoring on makroud. Maybe a huge / complex one ?
If that's the case, please discard my comments. I would like to see what you have in mind.

**Comment by yansal** [comment]
> So the real question is: what is the new scope of makroud ?

I think that's the key point. And that this PR goes against what we have in the README. I'll close this PR.

Personally, I would prefer makroud to be a collection of small packages that can be used independently, that interface well with the standard library, and that are driver-agnostic.

That was the idea behind the addition of sql hooks (https://github.com/ulule/makroud/pull/104): it's just a small package that can be used without pulling all of makroud.

Other independant packages would include building queries (that's loukoum), scanning *sql.Rows into structs/slice of structs/slices of interface{}/maps of interface{}/etc., nesting transactions, load balancing *sql.DBs, etc.

For certain features, we would have to combine multiple packages: typically for preloads, we need to both scan *sql.Rows into structs and build queries.

But in the general case, I want to be able to just use the features I need, and not pay the complexity of the whole package.

**Pull request closed without merging**
